server:
  port: 9000

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: fewbiuebeot5324980hbhgsd0uub9gpkklnqbp4214989oub926t32be0gbdsn

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true